name: Bug Report
description: Report a bug in pg-migration-lint
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of pg-migration-lint are you using?
      placeholder: e.g. 2.1.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: sql
    attributes:
      label: SQL input
      description: The SQL migration file(s) that trigger the bug.
      render: sql
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened? Include any error messages or output.
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your `pg-migration-lint.toml` (or relevant parts of it).
      render: toml
    validations:
      required: false

  - type: dropdown
    id: output-format
    attributes:
      label: Output format
      description: Which output format are you using?
      options:
        - text
        - sarif
        - sonarqube
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
        - Docker
        - Other
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, logs, or screenshots.
    validations:
      required: false
